//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonu.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HastaneOtomasyonuEntities : DbContext
    {
        public HastaneOtomasyonuEntities()
            : base("name=HastaneOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Branslar> Branslar { get; set; }
        public virtual DbSet<Doktorlar> Doktorlar { get; set; }
        public virtual DbSet<Hastalar> Hastalar { get; set; }
        public virtual DbSet<Randevular> Randevular { get; set; }
        public virtual DbSet<RandevuLog> RandevuLog { get; set; }
        public virtual DbSet<vw_RandevuDetaylari> vw_RandevuDetaylari { get; set; }
    
        public virtual ObjectResult<Nullable<int>> sp_DoktorRandevuSayisi(Nullable<int> doktorId)
        {
            var doktorIdParameter = doktorId.HasValue ?
                new ObjectParameter("DoktorId", doktorId) :
                new ObjectParameter("DoktorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DoktorRandevuSayisi", doktorIdParameter);
        }
    
        public virtual int sp_HastaBilgileriniGuncelle(Nullable<int> hastaId, string ad, string soyad, string tCNo, Nullable<System.DateTime> dogumTarihi)
        {
            var hastaIdParameter = hastaId.HasValue ?
                new ObjectParameter("HastaId", hastaId) :
                new ObjectParameter("HastaId", typeof(int));
    
            var adParameter = ad != null ?
                new ObjectParameter("Ad", ad) :
                new ObjectParameter("Ad", typeof(string));
    
            var soyadParameter = soyad != null ?
                new ObjectParameter("Soyad", soyad) :
                new ObjectParameter("Soyad", typeof(string));
    
            var tCNoParameter = tCNo != null ?
                new ObjectParameter("TCNo", tCNo) :
                new ObjectParameter("TCNo", typeof(string));
    
            var dogumTarihiParameter = dogumTarihi.HasValue ?
                new ObjectParameter("DogumTarihi", dogumTarihi) :
                new ObjectParameter("DogumTarihi", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HastaBilgileriniGuncelle", hastaIdParameter, adParameter, soyadParameter, tCNoParameter, dogumTarihiParameter);
        }
    
        public virtual int sp_HastaRandevuEkle(Nullable<int> hastaId, Nullable<int> doktorId, Nullable<System.DateTime> tarih, Nullable<System.TimeSpan> saat)
        {
            var hastaIdParameter = hastaId.HasValue ?
                new ObjectParameter("HastaId", hastaId) :
                new ObjectParameter("HastaId", typeof(int));
    
            var doktorIdParameter = doktorId.HasValue ?
                new ObjectParameter("DoktorId", doktorId) :
                new ObjectParameter("DoktorId", typeof(int));
    
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("Tarih", tarih) :
                new ObjectParameter("Tarih", typeof(System.DateTime));
    
            var saatParameter = saat.HasValue ?
                new ObjectParameter("Saat", saat) :
                new ObjectParameter("Saat", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HastaRandevuEkle", hastaIdParameter, doktorIdParameter, tarihParameter, saatParameter);
        }
    
        public virtual ObjectResult<sp_RandevuListeleByDoktor_Result> sp_RandevuListeleByDoktor(Nullable<int> doktorId)
        {
            var doktorIdParameter = doktorId.HasValue ?
                new ObjectParameter("DoktorId", doktorId) :
                new ObjectParameter("DoktorId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RandevuListeleByDoktor_Result>("sp_RandevuListeleByDoktor", doktorIdParameter);
        }
    
        public virtual int sp_RandevuSil(Nullable<int> randevuId)
        {
            var randevuIdParameter = randevuId.HasValue ?
                new ObjectParameter("RandevuId", randevuId) :
                new ObjectParameter("RandevuId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RandevuSil", randevuIdParameter);
        }
    }
}
