//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonu.Models
{
    public class Kullanici
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Sifre { get; set; }
    }
}
