//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevular
    {
        public int Id { get; set; }
        public Nullable<int> HastaId { get; set; }
        public Nullable<int> DoktorId { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
    
        public virtual Doktorlar Doktorlar { get; set; }
        public virtual Hastalar Hastalar { get; set; }
    }
}
