//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HastaneOtomasyonu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_RandevuDetaylari
    {
        public int RandevuId { get; set; }
        public string HastaAdSoyad { get; set; }
        public string DoktorAdSoyad { get; set; }
        public string Brans { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<System.TimeSpan> Saat { get; set; }
    }
}
